#### Final data of flood indicators for running the ML models

#### Data includes: Merged data from zenodo (till I-GUIDE), CEEW data, Flow accumulation, Historical flood data, and News data

In [1]:
merged_path = r'/Users/surabhiupadhyay/Documents/Projects/drought_perception_india/data/all_data/RAR_TEAM1_FinalCleanedData_250807.csv'
ceew_path = r'/Users/surabhiupadhyay/Documents/Projects/drought_perception_india/data/all_data/covariates_scaled_district.csv'
flow_acc_path = r'/Users/surabhiupadhyay/Documents/Projects/drought_perception_india/data/all_data/India_FlowAccumulation.csv'
flood_data_path = r'/Users/surabhiupadhyay/Documents/Projects/drought_perception_india/data/all_data/India_HistoricalFloods.csv'
news_path  = r'/Users/surabhiupadhyay/Documents/Projects/drought_perception_india/data/all_data/news_data_2024.csv'

In [2]:
import pandas as pd

merged_df = pd.read_csv(merged_path)
ceew_df   = pd.read_csv(ceew_path)
flow_df   = pd.read_csv(flow_acc_path)
flood_df  = pd.read_csv(flood_data_path)
news_df   = pd.read_csv(news_path)

In [22]:
merged_df

,Unnamed: 0.1,caseid,weight,wave,state,district,urban,gender,age,caste,...,A63_p90,A63_p95,A63_p98,A63_sum,A63_mean,A63_min,A63_max,A63_count,split,district_key
0,0,10001,0.840547,2024,NE,East Khasi Hills,Urban,Male,18-29,Scheduled Castes/Tribes,...,0.103406,0.124567,0.147697,43582.604336,0.012406,-0.267958,0.327812,3519450,train,east khasi hills
1,1,10002,1.360886,2024,UT,Leh,Rural,Female,45+,Scheduled Castes/Tribes,...,0.093564,0.141730,0.267958,-117536.992772,-0.024344,-0.318893,0.346021,4837249,train,leh
2,2,10002,1.360886,2024,UT,Leh,Rural,Female,45+,Scheduled Castes/Tribes,...,0.103406,0.130165,0.160000,-248714.921995,-0.038288,-0.327812,0.318893,6508506,train,leh
3,3,10003,0.640417,2024,UT,Daman & Diu,Rural,Male,30-44,Other Castes,...,0.221453,0.236463,0.244152,10633.937208,0.124858,-0.051734,0.355309,86148,train,daman & diu
4,4,10003,0.640417,2024,UT,Daman & Diu,Rural,Male,30-44,Other Castes,...,0.206936,0.244152,0.259900,4060.501217,0.087937,-0.113741,0.355309,47012,train,daman & diu
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11418,11418,22002,0.460300,2024,Rajasthan,Barmer,Rural,Male,18-29,Other Castes,...,0.071111,0.088827,0.108512,381161.657840,0.010840,-0.192910,0.403599,35184293,train,barmer
11419,11419,22003,0.850554,2024,Haryana,Kaithal,Rural,Male,18-29,Other Castes,...,0.135886,0.147697,0.166336,311378.842890,0.106551,-0.147697,0.364721,2929802,train,kaithal
11420,11420,22004,1.981290,2024,Jharkhand,Palamu,Rural,Male,18-29,Other Castes,...,0.108512,0.124567,0.153787,359997.778216,0.066570,-0.124567,0.327812,5416996,train,palamu
11421,11421,22005,0.490319,2024,Jammu & Kashmir,Kulgam,Rural,Male,45+,Other Castes,...,0.093564,0.141730,0.267958,-117536.992772,-0.024344,-0.318893,0.346021,4837249,train,kulgam
11422,11422,22005,0.490319,2024,Jammu & Kashmir,Kulgam,Rural,Male,45+,Other Castes,...,0.103406,0.130165,0.160000,-248714.921995,-0.038288,-0.327812,0.318893,6508506,train,kulgam

In [3]:
for name, df in {
    "merged": merged_df,
    "ceew": ceew_df,
    "flow": flow_df,
    "flood": flood_df,
    "news": news_df
}.items():
    print(f"\n{name.upper()} columns:")
    print(df.columns.tolist())

MERGED columns:
['Unnamed: 0.1', 'caseid', 'weight', 'wave', 'state', 'district', 'urban', 'gender', 'age', 'caste', 'n7dy23_recode', 'n7fy23_recode', 'state_district_survey', 'district_shapefile_code', 'di_code', 'districts', 'mean_monthly_avg_rd_MD', 'mean_monthly_avg_rd_MN', 'prep_year', 'precip_sum_mm', 'precip_mean_mm', 'mean_tmax', 'district_flood_sentiment', 'state_flood_sentiment', 'Unnamed: 0', 'state.1', 'state_district_survey.1', 'district_shapefile', 'st_code', 'state23', 'dist23', 'A00_p2', 'A00_p90', 'A00_p95', 'A00_p98', 'A00_sum', 'A00_mean', 'A00_min', 'A00_max', 'A00_count', 'A01_p2', 'A01_p90', 'A01_p95', 'A01_p98', 'A01_sum', 'A01_mean', 'A01_min', 'A01_max', 'A01_count', 'A02_p2', 'A02_p90', 'A02_p95', 'A02_p98', 'A02_sum', 'A02_mean', 'A02_min', 'A02_max', 'A02_count', 'A03_p2', 'A03_p90', 'A03_p95', 'A03_p98', 'A03_sum', 'A03_mean', 'A03_min', 'A03_max', 'A03_count', 'A04_p2', 'A04_p90', 'A04_p95', 'A04_p98', 'A04_sum', 'A04_mean', 'A04_min', 'A04_max', 'A04_count', 'A05_p2', 'A05_p90', 'A05_p95', 'A05_p98', 'A05_sum', 'A05_mean', 'A05_min', 'A05_max', 'A05_count', 'A06_p2', 'A06_p90', 'A06_p95', 'A06_p98', 'A06_sum', 'A06_mean', 'A06_min', 'A06_max', 'A06_count', 'A07_p2', 'A07_p90', 'A07_p95', 'A07_p98', 'A07_sum', 'A07_mean', 'A07_min', 'A07_max', 'A07_count', 'A08_p2', 'A08_p90', 'A08_p95', 'A08_p98', 'A08_sum', 'A08_mean', 'A08_min', 'A08_max', 'A08_count', 'A09_p2', 'A09_p90', 'A09_p95', 'A09_p98', 'A09_sum', 'A09_mean', 'A09_min', 'A09_max', 'A09_count', 'A10_p2', 'A10_p90', 'A10_p95', 'A10_p98', 'A10_sum', 'A10_mean', 'A10_min', 'A10_max', 'A10_count', 'A11_p2', 'A11_p90', 'A11_p95', 'A11_p98', 'A11_sum', 'A11_mean', 'A11_min', 'A11_max', 'A11_count', 'A12_p2', 'A12_p90', 'A12_p95', 'A12_p98', 'A12_sum', 'A12_mean', 'A12_min', 'A12_max', 'A12_count', 'A13_p2', 'A13_p90', 'A13_p95', 'A13_p98', 'A13_sum', 'A13_mean', 'A13_min', 'A13_max', 'A13_count', 'A14_p2', 'A14_p90', 'A14_p95', 'A14_p98', 'A14_sum', 'A14_mean', 'A14_min', 'A14_max', 'A14_count', 'A15_p2', 'A15_p90', 'A15_p95', 'A15_p98', 'A15_sum', 'A15_mean', 'A15_min', 'A15_max', 'A15_count', 'A16_p2', 'A16_p90', 'A16_p95', 'A16_p98', 'A16_sum', 'A16_mean', 'A16_min', 'A16_max', 'A16_count', 'A17_p2', 'A17_p90', 'A17_p95', 'A17_p98', 'A17_sum', 'A17_mean', 'A17_min', 'A17_max', 'A17_count', 'A18_p2', 'A18_p90', 'A18_p95', 'A18_p98', 'A18_sum', 'A18_mean', 'A18_min', 'A18_max', 'A18_count', 'A19_p2', 'A19_p90', 'A19_p95', 'A19_p98', 'A19_sum', 'A19_mean', 'A19_min', 'A19_max', 'A19_count', 'A20_p2', 'A20_p90', 'A20_p95', 'A20_p98', 'A20_sum', 'A20_mean', 'A20_min', 'A20_max', 'A20_count', 'A21_p2', 'A21_p90', 'A21_p95', 'A21_p98', 'A21_sum', 'A21_mean', 'A21_min', 'A21_max', 'A21_count', 'A22_p2', 'A22_p90', 'A22_p95', 'A22_p98', 'A22_sum', 'A22_mean', 'A22_min', 'A22_max', 'A22_count', 'A23_p2', 'A23_p90', 'A23_p95', 'A23_p98', 'A23_sum', 'A23_mean', 'A23_min', 'A23_max', 'A23_count', 'A24_p2', 'A24_p90', 'A24_p95', 'A24_p98', 'A24_sum', 'A24_mean', 'A24_min', 'A24_max', 'A24_count', 'A25_p2', 'A25_p90', 'A25_p95', 'A25_p98', 'A25_sum', 'A25_mean', 'A25_min', 'A25_max', 'A25_count', 'A26_p2', 'A26_p90', 'A26_p95', 'A26_p98', 'A26_sum', 'A26_mean', 'A26_min', 'A26_max', 'A26_count', 'A27_p2', 'A27_p90', 'A27_p95', 'A27_p98', 'A27_sum', 'A27_mean', 'A27_min', 'A27_max', 'A27_count', 'A28_p2', 'A28_p90', 'A28_p95', 'A28_p98', 'A28_sum', 'A28_mean', 'A28_min', 'A28_max', 'A28_count', 'A29_p2', 'A29_p90', 'A29_p95', 'A29_p98', 'A29_sum', 'A29_mean', 'A29_min', 'A29_max', 'A29_count', 'A30_p2', 'A30_p90', 'A30_p95', 'A30_p98', 'A30_sum', 'A30_mean', 'A30_min', 'A30_max', 'A30_count', 'A31_p2', 'A31_p90', 'A31_p95', 'A31_p98', 'A31_sum', 'A31_mean', 'A31_min', 'A31_max', 'A31_count', 'A32_p2', 'A32_p90', 'A32_p95', 'A32_p98', 'A32_sum', 'A32_mean', 'A32_min', 'A32_max', 'A32_count', 'A33_p2', 'A33_p90', 'A33_p95', 'A33_p98', 'A33_sum', 'A33_mean', 'A33_min', 'A33_max', 'A33_count', 'A34_p2', 'A34_p90', 'A34_p95', 'A34_p98', 'A34_sum', 'A34_mean', 'A34_min', 'A34_max', 'A34_count', 'A35_p2', 'A35_p90', 'A35_p95', 'A35_p98', 'A35_sum', 'A35_mean', 'A35_min', 'A35_max', 'A35_count', 'A36_p2', 'A36_p90', 'A36_p95', 'A36_p98', 'A36_sum', 'A36_mean', 'A36_min', 'A36_max', 'A36_count', 'A37_p2', 'A37_p90', 'A37_p95', 'A37_p98', 'A37_sum', 'A37_mean', 'A37_min', 'A37_max', 'A37_count', 'A38_p2', 'A38_p90', 'A38_p95', 'A38_p98', 'A38_sum', 'A38_mean', 'A38_min', 'A38_max', 'A38_count', 'A39_p2', 'A39_p90', 'A39_p95', 'A39_p98', 'A39_sum', 'A39_mean', 'A39_min', 'A39_max', 'A39_count', 'A40_p2', 'A40_p90', 'A40_p95', 'A40_p98', 'A40_sum', 'A40_mean', 'A40_min', 'A40_max', 'A40_count', 'A41_p2', 'A41_p90', 'A41_p95', 'A41_p98', 'A41_sum', 'A41_mean', 'A41_min', 'A41_max', 'A41_count', 'A42_p2', 'A42_p90', 'A42_p95', 'A42_p98', 'A42_sum', 'A42_mean', 'A42_min', 'A42_max', 'A42_count', 'A43_p2', 'A43_p90', 'A43_p95', 'A43_p98', 'A43_sum', 'A43_mean', 'A43_min', 'A43_max', 'A43_count', 'A44_p2', 'A44_p90', 'A44_p95', 'A44_p98', 'A44_sum', 'A44_mean', 'A44_min', 'A44_max', 'A44_count', 'A45_p2', 'A45_p90', 'A45_p95', 'A45_p98', 'A45_sum', 'A45_mean', 'A45_min', 'A45_max', 'A45_count', 'A46_p2', 'A46_p90', 'A46_p95', 'A46_p98', 'A46_sum', 'A46_mean', 'A46_min', 'A46_max', 'A46_count', 'A47_p2', 'A47_p90', 'A47_p95', 'A47_p98', 'A47_sum', 'A47_mean', 'A47_min', 'A47_max', 'A47_count', 'A48_p2', 'A48_p90', 'A48_p95', 'A48_p98', 'A48_sum', 'A48_mean', 'A48_min', 'A48_max', 'A48_count', 'A49_p2', 'A49_p90', 'A49_p95', 'A49_p98', 'A49_sum', 'A49_mean', 'A49_min', 'A49_max', 'A49_count', 'A50_p2', 'A50_p90', 'A50_p95', 'A50_p98', 'A50_sum', 'A50_mean', 'A50_min', 'A50_max', 'A50_count', 'A51_p2', 'A51_p90', 'A51_p95', 'A51_p98', 'A51_sum', 'A51_mean', 'A51_min', 'A51_max', 'A51_count', 'A52_p2', 'A52_p90', 'A52_p95', 'A52_p98', 'A52_sum', 'A52_mean', 'A52_min', 'A52_max', 'A52_count', 'A53_p2', 'A53_p90', 'A53_p95', 'A53_p98', 'A53_sum', 'A53_mean', 'A53_min', 'A53_max', 'A53_count', 'A54_p2', 'A54_p90', 'A54_p95', 'A54_p98', 'A54_sum', 'A54_mean', 'A54_min', 'A54_max', 'A54_count', 'A55_p2', 'A55_p90', 'A55_p95', 'A55_p98', 'A55_sum', 'A55_mean', 'A55_min', 'A55_max', 'A55_count', 'A56_p2', 'A56_p90', 'A56_p95', 'A56_p98', 'A56_sum', 'A56_mean', 'A56_min', 'A56_max', 'A56_count', 'A57_p2', 'A57_p90', 'A57_p95', 'A57_p98', 'A57_sum', 'A57_mean', 'A57_min', 'A57_max', 'A57_count', 'A58_p2', 'A58_p90', 'A58_p95', 'A58_p98', 'A58_sum', 'A58_mean', 'A58_min', 'A58_max', 'A58_count', 'A59_p2', 'A59_p90', 'A59_p95', 'A59_p98', 'A59_sum', 'A59_mean', 'A59_min', 'A59_max', 'A59_count', 'A60_p2', 'A60_p90', 'A60_p95', 'A60_p98', 'A60_sum', 'A60_mean', 'A60_min', 'A60_max', 'A60_count', 'A61_p2', 'A61_p90', 'A61_p95', 'A61_p98', 'A61_sum', 'A61_mean', 'A61_min', 'A61_max', 'A61_count', 'A62_p2', 'A62_p90', 'A62_p95', 'A62_p98', 'A62_sum', 'A62_mean', 'A62_min', 'A62_max', 'A62_count', 'A63_p2', 'A63_p90', 'A63_p95', 'A63_p98', 'A63_sum', 'A63_mean', 'A63_min', 'A63_max', 'A63_count', 'split']

CEEW columns:
['state_census', 'state_survey', 'district_census', 'district_survey', 'state_dist', 'N', 'highersecondaryabove_district', 'vulnerability_district']

FLOW columns:
['system:index', 'FlowAcc_sum', 'GEOID', 'GeoName', 'Shape_Area', 'Shape_Leng', 'di_code', 'dist23', 'st_code', 'st_di23', 'state23', '.geo']

FLOOD columns:
['system:index', 'GEOID', 'GFD_sum', 'GeoName', 'Shape_Area', 'Shape_Leng', 'di_code', 'dist23', 'st_code', 'st_di23', 'state23', '.geo']

NEWS columns:
['DATE', 'District', 'State', 'EventType', 'MatchedTheme', 'SOURCES', 'SOURCEURLS', 'Tone_Avg', 'Tone_Positive', 'Tone_Negative', 'Tone_Polarity', 'Tone_ActivityRef', 'Tone_SelfGroupRef', 'domain', 'has_keyword', 'snippet', 'matched_keyword', 'District_Clean', 'State_Clean', 'Country', 'Date', 'Year', 'Month', 'Month_Name']

In [9]:
# Make simple merge keys
merged_df["district_key"] = merged_df["district"].astype(str).str.lower().str.strip()
ceew_df["district_key"]   = ceew_df["district_survey"].astype(str).str.lower().str.strip()
news_df["district_key"]   = news_df["District_Clean"].astype(str).str.lower().str.strip()

In [10]:
#CEEW: one row per district
ceew_small = (ceew_df
    .groupby("district_key", as_index=False)
    .agg({
        "highersecondaryabove_district": "mean",
        "vulnerability_district": "mean",
        "N": "mean"
    })
)

In [11]:
# Flow + Flood: one row per di_code
flow_small  = flow_df[["di_code", "FlowAcc_sum"]].drop_duplicates("di_code")
flood_small = flood_df[["di_code", "GFD_sum"]].drop_duplicates("di_code")

In [12]:
# News: keep only Flood, then one row per district
news_df = news_df[news_df["EventType"] == "Flood"].copy()

news_small = (news_df
    .groupby("district_key", as_index=False)
    .agg({
        "SOURCEURLS": "count",
        "Tone_Avg": "mean",
        "Tone_Positive": "mean",
        "Tone_Negative": "mean",
        "Tone_Polarity": "mean",
        "Tone_ActivityRef": "mean",
        "Tone_SelfGroupRef": "mean",
    })
    .rename(columns={"SOURCEURLS": "flood_news_count"})
)

In [13]:
# Merge all into survey data
df = merged_df.merge(ceew_small, on="district_key", how="left")
df = df.merge(flow_small, on="di_code", how="left")
df = df.merge(flood_small, on="di_code", how="left")
df = df.merge(news_small, on="district_key", how="left")

In [16]:
df.columns.tolist()

['Unnamed: 0.1',
 'caseid',
 'weight',
 'wave',
 'state',
 'district',
 'urban',
 'gender',
 'age',
 'caste',
 'n7dy23_recode',
 'n7fy23_recode',
 'state_district_survey',
 'district_shapefile_code',
 'di_code',
 'districts',
 'mean_monthly_avg_rd_MD',
 'mean_monthly_avg_rd_MN',
 'prep_year',
 'precip_sum_mm',
 'precip_mean_mm',
 'mean_tmax',
 'district_flood_sentiment',
 'state_flood_sentiment',
 'Unnamed: 0',
 'state.1',
 'state_district_survey.1',
 'district_shapefile',
 'st_code',
 'state23',
 'dist23',
 'A00_p2',
 'A00_p90',
 'A00_p95',
 'A00_p98',
 'A00_sum',
 'A00_mean',
 'A00_min',
 'A00_max',
 'A00_count',
 'A01_p2',
 'A01_p90',
 'A01_p95',
 'A01_p98',
 'A01_sum',
 'A01_mean',
 'A01_min',
 'A01_max',
 'A01_count',
 'A02_p2',
 'A02_p90',
 'A02_p95',
 'A02_p98',
 'A02_sum',
 'A02_mean',
 'A02_min',
 'A02_max',
 'A02_count',
 'A03_p2',
 'A03_p90',
 'A03_p95',
 'A03_p98',
 'A03_sum',
 'A03_mean',
 'A03_min',
 'A03_max',
 'A03_count',
 'A04_p2',
 'A04_p90',
 'A04_p95',
 'A04_p98',
 'A04_sum',
 'A04_mean',
 'A04_min',
 'A04_max',
 'A04_count',
 'A05_p2',
 'A05_p90',
 'A05_p95',
 'A05_p98',
 'A05_sum',
 'A05_mean',
 'A05_min',
 'A05_max',
 'A05_count',
 'A06_p2',
 'A06_p90',
 'A06_p95',
 'A06_p98',
 'A06_sum',
 'A06_mean',
 'A06_min',
 'A06_max',
 'A06_count',
 'A07_p2',
 'A07_p90',
 'A07_p95',
 'A07_p98',
 'A07_sum',
 'A07_mean',
 'A07_min',
 'A07_max',
 'A07_count',
 'A08_p2',
 'A08_p90',
 'A08_p95',
 'A08_p98',
 'A08_sum',
 'A08_mean',
 'A08_min',
 'A08_max',
 'A08_count',
 'A09_p2',
 'A09_p90',
 'A09_p95',
 'A09_p98',
 'A09_sum',
 'A09_mean',
 'A09_min',
 'A09_max',
 'A09_count',
 'A10_p2',
 'A10_p90',
 'A10_p95',
 'A10_p98',
 'A10_sum',
 'A10_mean',
 'A10_min',
 'A10_max',
 'A10_count',
 'A11_p2',
 'A11_p90',
 'A11_p95',
 'A11_p98',
 'A11_sum',
 'A11_mean',
 'A11_min',
 'A11_max',
 'A11_count',
 'A12_p2',
 'A12_p90',
 'A12_p95',
 'A12_p98',
 'A12_sum',
 'A12_mean',
 'A12_min',
 'A12_max',
 'A12_count',
 'A13_p2',
 'A13_p90',
 'A13_p95',
 'A13_p98',
 'A13_sum',
 'A13_mean',
 'A13_min',
 'A13_max',
 'A13_count',
 'A14_p2',
 'A14_p90',
 'A14_p95',
 'A14_p98',
 'A14_sum',
 'A14_mean',
 'A14_min',
 'A14_max',
 'A14_count',
 'A15_p2',
 'A15_p90',
 'A15_p95',
 'A15_p98',
 'A15_sum',
 'A15_mean',
 'A15_min',
 'A15_max',
 'A15_count',
 'A16_p2',
 'A16_p90',
 'A16_p95',
 'A16_p98',
 'A16_sum',
 'A16_mean',
 'A16_min',
 'A16_max',
 'A16_count',
 'A17_p2',
 'A17_p90',
 'A17_p95',
 'A17_p98',
 'A17_sum',
 'A17_mean',
 'A17_min',
 'A17_max',
 'A17_count',
 'A18_p2',
 'A18_p90',
 'A18_p95',
 'A18_p98',
 'A18_sum',
 'A18_mean',
 'A18_min',
 'A18_max',
 'A18_count',
 'A19_p2',
 'A19_p90',
 'A19_p95',
 'A19_p98',
 'A19_sum',
 'A19_mean',
 'A19_min',
 'A19_max',
 'A19_count',
 'A20_p2',
 'A20_p90',
 'A20_p95',
 'A20_p98',
 'A20_sum',
 'A20_mean',
 'A20_min',
 'A20_max',
 'A20_count',
 'A21_p2',
 'A21_p90',
 'A21_p95',
 'A21_p98',
 'A21_sum',
 'A21_mean',
 'A21_min',
 'A21_max',
 'A21_count',
 'A22_p2',
 'A22_p90',
 'A22_p95',
 'A22_p98',
 'A22_sum',
 'A22_mean',
 'A22_min',
 'A22_max',
 'A22_count',
 'A23_p2',
 'A23_p90',
 'A23_p95',
 'A23_p98',
 'A23_sum',
 'A23_mean',
 'A23_min',
 'A23_max',
 'A23_count',
 'A24_p2',
 'A24_p90',
 'A24_p95',
 'A24_p98',
 'A24_sum',
 'A24_mean',
 'A24_min',
 'A24_max',
 'A24_count',
 'A25_p2',
 'A25_p90',
 'A25_p95',
 'A25_p98',
 'A25_sum',
 'A25_mean',
 'A25_min',
 'A25_max',
 'A25_count',
 'A26_p2',
 'A26_p90',
 'A26_p95',
 'A26_p98',
 'A26_sum',
 'A26_mean',
 'A26_min',
 'A26_max',
 'A26_count',
 'A27_p2',
 'A27_p90',
 'A27_p95',
 'A27_p98',
 'A27_sum',
 'A27_mean',
 'A27_min',
 'A27_max',
 'A27_count',
 'A28_p2',
 'A28_p90',
 'A28_p95',
 'A28_p98',
 'A28_sum',
 'A28_mean',
 'A28_min',
 'A28_max',
 'A28_count',
 'A29_p2',
 'A29_p90',
 'A29_p95',
 'A29_p98',
 'A29_sum',
 'A29_mean',
 'A29_min',
 'A29_max',
 'A29_count',
 'A30_p2',
 'A30_p90',
 'A30_p95',
 'A30_p98',
 'A30_sum',
 'A30_mean',
 'A30_min',
 'A30_max',
 'A30_count',
 'A31_p2',
 'A31_p90',
 'A31_p95',
 'A31_p98',
 'A31_sum',
 'A31_mean',
 'A31_min',
 'A31_max',
 'A31_count',
 'A32_p2',
 'A32_p90',
 'A32_p95',
 'A32_p98',
 'A32_sum',
 'A32_mean',
 'A32_min',
 'A32_max',
 'A32_count',
 'A33_p2',
 'A33_p90',
 'A33_p95',
 'A33_p98',
 'A33_sum',
 'A33_mean',
 'A33_min',
 'A33_max',
 'A33_count',
 'A34_p2',
 'A34_p90',
 'A34_p95',
 'A34_p98',
 'A34_sum',
 'A34_mean',
 'A34_min',
 'A34_max',
 'A34_count',
 'A35_p2',
 'A35_p90',
 'A35_p95',
 'A35_p98',
 'A35_sum',
 'A35_mean',
 'A35_min',
 'A35_max',
 'A35_count',
 'A36_p2',
 'A36_p90',
 'A36_p95',
 'A36_p98',
 'A36_sum',
 'A36_mean',
 'A36_min',
 'A36_max',
 'A36_count',
 'A37_p2',
 'A37_p90',
 'A37_p95',
 'A37_p98',
 'A37_sum',
 'A37_mean',
 'A37_min',
 'A37_max',
 'A37_count',
 'A38_p2',
 'A38_p90',
 'A38_p95',
 'A38_p98',
 'A38_sum',
 'A38_mean',
 'A38_min',
 'A38_max',
 'A38_count',
 'A39_p2',
 'A39_p90',
 'A39_p95',
 'A39_p98',
 'A39_sum',
 'A39_mean',
 'A39_min',
 'A39_max',
 'A39_count',
 'A40_p2',
 'A40_p90',
 'A40_p95',
 'A40_p98',
 'A40_sum',
 'A40_mean',
 'A40_min',
 'A40_max',
 'A40_count',
 'A41_p2',
 'A41_p90',
 'A41_p95',
 'A41_p98',
 'A41_sum',
 'A41_mean',
 'A41_min',
 'A41_max',
 'A41_count',
 'A42_p2',
 'A42_p90',
 'A42_p95',
 'A42_p98',
 'A42_sum',
 'A42_mean',
 'A42_min',
 'A42_max',
 'A42_count',
 'A43_p2',
 'A43_p90',
 'A43_p95',
 'A43_p98',
 'A43_sum',
 'A43_mean',
 'A43_min',
 'A43_max',
 'A43_count',
 'A44_p2',
 'A44_p90',
 'A44_p95',
 'A44_p98',
 'A44_sum',
 'A44_mean',
 'A44_min',
 'A44_max',
 'A44_count',
 'A45_p2',
 'A45_p90',
 'A45_p95',
 'A45_p98',
 'A45_sum',
 'A45_mean',
 'A45_min',
 'A45_max',
 'A45_count',
 'A46_p2',
 'A46_p90',
 'A46_p95',
 'A46_p98',
 'A46_sum',
 'A46_mean',
 'A46_min',
 'A46_max',
 'A46_count',
 'A47_p2',
 'A47_p90',
 'A47_p95',
 'A47_p98',
 'A47_sum',
 'A47_mean',
 'A47_min',
 'A47_max',
 'A47_count',
 'A48_p2',
 'A48_p90',
 'A48_p95',
 'A48_p98',
 'A48_sum',
 'A48_mean',
 'A48_min',
 'A48_max',
 'A48_count',
 'A49_p2',
 'A49_p90',
 'A49_p95',
 'A49_p98',
 'A49_sum',
 'A49_mean',
 'A49_min',
 'A49_max',
 'A49_count',
 'A50_p2',
 'A50_p90',
 'A50_p95',
 'A50_p98',
 'A50_sum',
 'A50_mean',
 'A50_min',
 'A50_max',
 'A50_count',
 'A51_p2',
 'A51_p90',
 'A51_p95',
 'A51_p98',
 'A51_sum',
 'A51_mean',
 'A51_min',
 'A51_max',
 'A51_count',
 'A52_p2',
 'A52_p90',
 'A52_p95',
 'A52_p98',
 'A52_sum',
 'A52_mean',
 'A52_min',
 'A52_max',
 'A52_count',
 'A53_p2',
 'A53_p90',
 'A53_p95',
 'A53_p98',
 'A53_sum',
 'A53_mean',
 'A53_min',
 'A53_max',
 'A53_count',
 'A54_p2',
 'A54_p90',
 'A54_p95',
 'A54_p98',
 'A54_sum',
 'A54_mean',
 'A54_min',
 'A54_max',
 'A54_count',
 'A55_p2',
 'A55_p90',
 'A55_p95',
 'A55_p98',
 'A55_sum',
 'A55_mean',
 'A55_min',
 'A55_max',
 'A55_count',
 'A56_p2',
 'A56_p90',
 'A56_p95',
 'A56_p98',
 'A56_sum',
 'A56_mean',
 'A56_min',
 'A56_max',
 'A56_count',
 'A57_p2',
 'A57_p90',
 'A57_p95',
 'A57_p98',
 'A57_sum',
 'A57_mean',
 'A57_min',
 'A57_max',
 'A57_count',
 'A58_p2',
 'A58_p90',
 'A58_p95',
 'A58_p98',
 'A58_sum',
 'A58_mean',
 'A58_min',
 'A58_max',
 'A58_count',
 'A59_p2',
 'A59_p90',
 'A59_p95',
 'A59_p98',
 'A59_sum',
 'A59_mean',
 'A59_min',
 'A59_max',
 'A59_count',
 'A60_p2',
 'A60_p90',
 'A60_p95',
 'A60_p98',
 'A60_sum',
 'A60_mean',
 'A60_min',
 'A60_max',
 'A60_count',
 'A61_p2',
 'A61_p90',
 'A61_p95',
 'A61_p98',
 'A61_sum',
 'A61_mean',
 'A61_min',
 'A61_max',
 'A61_count',
 'A62_p2',
 'A62_p90',
 'A62_p95',
 'A62_p98',
 'A62_sum',
 'A62_mean',
 'A62_min',
 'A62_max',
 'A62_count',
 'A63_p2',
 'A63_p90',
 'A63_p95',
 'A63_p98',
 'A63_sum',
 'A63_mean',
 'A63_min',
 'A63_max',
 'A63_count',
 'split',
 'district_key',
 'highersecondaryabove_district',
 'vulnerability_district',
 'N',
 'FlowAcc_sum',
 'GFD_sum',
 'flood_news_count',
 'Tone_Avg',
 'Tone_Positive',
 'Tone_Negative',
 'Tone_Polarity',
 'Tone_ActivityRef',
 'Tone_SelfGroupRef']

In [24]:
# columns to remove
cols_to_drop = [
    "district_flood_sentiment",
    "state_flood_sentiment",
    "Unnamed: 0",
    "state.1",
    "state_district_survey.1",
    "district_shapefile", 
    "N",
    "split",
    "n7dy23_recode"
]

# drop safely (won’t error if a column is missing)
df = df.drop(columns=[c for c in cols_to_drop if c in df.columns])

In [25]:
df

,Unnamed: 0.1,caseid,weight,wave,state,district,urban,gender,age,caste,...,vulnerability_district,FlowAcc_sum,GFD_sum,flood_news_count,Tone_Avg,Tone_Positive,Tone_Negative,Tone_Polarity,Tone_ActivityRef,Tone_SelfGroupRef
0,0,10001,0.840547,2024,NE,East Khasi Hills,Urban,Male,18-29,Scheduled Castes/Tribes,...,-0.816196,7.340252e+05,698.843137,1.0,-7.284768,0.496689,7.781457,8.278146,20.198676,0.165563
1,1,10002,1.360886,2024,UT,Leh,Rural,Female,45+,Scheduled Castes/Tribes,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,10002,1.360886,2024,UT,Leh,Rural,Female,45+,Scheduled Castes/Tribes,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,10003,0.640417,2024,UT,Daman & Diu,Rural,Male,30-44,Other Castes,...,-0.816196,2.023339e+05,230.176471,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,10003,0.640417,2024,UT,Daman & Diu,Rural,Male,30-44,Other Castes,...,-0.816196,2.023339e+05,230.176471,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11418,11418,22002,0.460300,2024,Rajasthan,Barmer,Rural,Male,18-29,Other Castes,...,1.939687,1.066204e+08,2005.690196,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11419,11419,22003,0.850554,2024,Haryana,Kaithal,Rural,Male,18-29,Other Castes,...,-0.816196,2.788392e+06,15119.490196,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11420,11420,22004,1.981290,2024,Jharkhand,Palamu,Rural,Male,18-29,Other Castes,...,-0.816196,1.496580e+07,4664.152941,1.0,-5.555556,0.617284,6.172840,6.790123,21.913580,0.925926
11421,11421,22005,0.490319,2024,Jammu & Kashmir,Kulgam,Rural,Male,45+,Other Castes,...,NaN,NaN,NaN,1.0,-6.713781,0.353357,7.067138,7.420495,21.908127,0.000000
11422,11422,22005,0.490319,2024,Jammu & Kashmir,Kulgam,Rural,Male,45+,Other Castes,...,NaN,NaN,NaN,1.0,-6.713781,0.353357,7.067138,7.420495,21.908127,0.000000

In [26]:
df.to_csv("/Users/surabhiupadhyay/Documents/Projects/drought_perception_india/data/all_data/RAP_Flood_merged_all.csv", index=False)